name: Vincent OS Issue
description: For any issues about the Vincent OS version.
title: "[BUG] "
labels: bug, vincent-os
assignees:
  - florian-at-v38armageddon

body:
  - type: markdown
    attributes:
      value: |
        <!-- **!!!PLEASE READ THIS BEFORE SUBMITTING A ISSUE!!!**
          When submitting a issue:
          - Please search to avoid duplicate.
          - Detail as much as you can your problem.
          - If possible, include screenshots of the problems
          - If the issue is from a third-part software, do not post here. Post on their bug report page. -->
  - type: textarea
    id: describe
    attributes:
      label: Describe the problem
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to Reproduce the problem?
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Past your screenshot here.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: logs
      description: If applicable, add logs to be able to reproduce the issue.
      placeholder: Past your logs here via a .log file or full text.
  - type: markdown
    id: computer
    attributes:
      value: |
        ## Your computer information
  - type: input
    id: informations
    attributes:
      label: Your setup informations
      description: Provide your computer informations by selecting 'Copy details' in 'About this system' from the Info Center. 
    validations:
      required: true
  - type: input
    id: edition
    attributes:
      label: Vincent OS Edition
      placeholder: e.g. Vincent OS Standard Edition
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
